# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.SmallIntegerField(choices=[(0, 'admin'), (1, 'operator')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
