# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170519_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='line',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
