from django.db import models
from conduit.apps.core.models import TimestampModel


class Report(TimestampModel):
    unit = models.ForeignKey('units.Unit', null=False, related_name='reports', on_delete=models.CASCADE)
    gsm_imei = models.CharField(max_length=64, blank=True)
    time = models.DateTimeField()
    usDistMsr1 = models.IntegerField()
    usDistAlmSet1 = models.IntegerField()
    usDistMsr2 = models.IntegerField()
    usDistAlmSet2 = models.IntegerField()
    usDistMsr3 = models.IntegerField()
    usDistAlmSet3 = models.IntegerField()
    message = models.CharField(max_length=255, blank=True)
    isAlert = models.BooleanField(default=False)
    ackTime = models.DateTimeField(null=True, blank=True)
    ackMethod = models.SmallIntegerField(null=True, blank=True)
    ackOperator = models.ForeignKey('authentication.User', null=True, blank=True,related_name='ackedreports', on_delete=models.CASCADE)
    ackDetail = models.CharField(max_length=64, blank=True)
    mediaGuid = models.CharField(max_length=64, blank=True)
    hasMedia = models.BooleanField(default=False)
    infoId = models.IntegerField(null=True)
    weather = models.CharField(max_length=64, blank=True)
    mediaTypeCamera1 = models.SmallIntegerField(null=True, blank=True)
    mediaTypeCamera2 = models.SmallIntegerField(null=True, blank=True)
    mediaTypeCamera3 = models.SmallIntegerField(null=True, blank=True)
    camFrameRate1 = models.SmallIntegerField(null=True)
    camVideoTimeLen1 = models.SmallIntegerField(null=True)
    camFrameRate2 = models.SmallIntegerField(null=True)
    camVideoTimeLen2 = models.SmallIntegerField(null=True)
    camFrameRate3 = models.SmallIntegerField(null=True)
    camVideoTimeLen3 = models.SmallIntegerField(null=True)
    simpleGuid = models.CharField(max_length=64, blank=True)
    simpleLength1 = models.SmallIntegerField(null=True)
    simpleLength2 = models.SmallIntegerField(null=True)
    simpleLength3 = models.SmallIntegerField(null=True)
    sensMode = models.BooleanField(default=True)
    beepEnable = models.BooleanField(default=True)
    CSQ = models.SmallIntegerField(null=True)
    netState = models.SmallIntegerField(null=True)
    dumpEnergy = models.SmallIntegerField(null=True)
    temp = models.SmallIntegerField(null=True)
    hardwareVer = models.IntegerField(null=True)
    firmwareVer = models.IntegerField(null=True)
    powerLineVoltage = models.SmallIntegerField(null=True)
    powerLineCurr = models.CharField(max_length=65535, blank=True)
    powerLineTemp = models.CharField(max_length=65535, blank=True)
    powerLineVibr = models.CharField(max_length=65535, blank=True)

    def __str__(self):
        return self.time.strftime('%b %d %Y %H:%M:%S') + ":" + self.unit.name + ":" + self.message

