# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gsm_imei', models.CharField(blank=True, max_length=64)),
                ('time', models.DateTimeField()),
                ('usDistMsr1', models.IntegerField()),
                ('usDistAlmSet1', models.IntegerField()),
                ('usDistMsr2', models.IntegerField()),
                ('usDistAlmSet2', models.IntegerField()),
                ('usDistMsr3', models.IntegerField()),
                ('usDistAlmSet3', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=255)),
                ('isAlert', models.BooleanField(default=False)),
                ('ackTime', models.DateTimeField(blank=True, null=True)),
                ('ackMethod', models.SmallIntegerField(blank=True, null=True)),
                ('ackDetail', models.CharField(blank=True, max_length=64)),
                ('mediaGuid', models.CharField(blank=True, max_length=64)),
                ('hasNedia', models.BooleanField(default=False)),
                ('infoId', models.IntegerField(null=True)),
                ('weather', models.CharField(blank=True, max_length=64)),
                ('mediaTypeCamera1', models.SmallIntegerField(blank=True, null=True)),
                ('mediaTypeCamera2', models.SmallIntegerField(blank=True, null=True)),
                ('mediaTypeCamera3', models.SmallIntegerField(blank=True, null=True)),
                ('camFrameRate1', models.SmallIntegerField(null=True)),
                ('camVideoTimeLen1', models.SmallIntegerField(null=True)),
                ('camFrameRate2', models.SmallIntegerField(null=True)),
                ('camVideoTimeLen2', models.SmallIntegerField(null=True)),
                ('camFrameRate3', models.SmallIntegerField(null=True)),
                ('camVideoTimeLen3', models.SmallIntegerField(null=True)),
                ('simpleGuid', models.CharField(blank=True, max_length=64)),
                ('simpleLength1', models.SmallIntegerField(null=True)),
                ('simpleLength2', models.SmallIntegerField(null=True)),
                ('simpleLength3', models.SmallIntegerField(null=True)),
                ('sensMode', models.BooleanField(default=True)),
                ('beepEnable', models.BooleanField(default=True)),
                ('CSQ', models.SmallIntegerField(null=True)),
                ('netState', models.SmallIntegerField(null=True)),
                ('dumpEnergy', models.SmallIntegerField(null=True)),
                ('temp', models.SmallIntegerField(null=True)),
                ('hardwareVer', models.IntegerField(null=True)),
                ('firmwareVer', models.IntegerField(null=True)),
                ('powerLineVoltage', models.SmallIntegerField(null=True)),
                ('powerLineCurr', models.CharField(blank=True, max_length=65535)),
                ('powerLineTemp', models.CharField(blank=True, max_length=65535)),
                ('powerLineVibr', models.CharField(blank=True, max_length=65535)),
                ('ackOperator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ackedreports', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='units.Unit')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
