# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('distance1current', models.IntegerField()),
                ('distance1quota', models.IntegerField()),
                ('distance2current', models.IntegerField()),
                ('distance2quota', models.IntegerField()),
                ('distance3current', models.IntegerField()),
                ('distance3quota', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=255)),
                ('isalert', models.BooleanField(default=False)),
                ('acktime', models.DateTimeField(null=True)),
                ('ackmethod', models.SmallIntegerField()),
                ('ackdetail', models.CharField(blank=True, max_length=64)),
                ('mediaguid', models.CharField(blank=True, max_length=64)),
                ('hasmedia', models.BooleanField(default=False)),
                ('statusid', models.IntegerField()),
                ('weather', models.CharField(max_length=64)),
                ('mediatypecamera1', models.SmallIntegerField()),
                ('mediatypecamera2', models.SmallIntegerField()),
                ('mediatypecamera3', models.SmallIntegerField()),
                ('ackoperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ackedreports', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
