# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='hasNedia',
            new_name='hasMedia',
        ),
    ]
