# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ackmethod',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ackoperator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ackedreports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='acktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='mediatypecamera1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='mediatypecamera2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='mediatypecamera3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='weather',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
