# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170519_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ackmethod',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
