# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170801_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
