# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('type', models.SmallIntegerField(default=0)),
                ('parameter', models.SmallIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
