# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sms',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='units.Unit'),
        ),
    ]
