# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
