# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-28 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'city'), (1, 'line'), (2, 'unit')])),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('isShared', models.BooleanField(default=False)),
                ('voltage', models.CharField(blank=True, db_index=True, max_length=32)),
                ('phoneNum', models.CharField(blank=True, db_index=True, max_length=32)),
                ('backPhoneNum', models.CharField(blank=True, max_length=32)),
                ('backPhoneUsed', models.BooleanField(default=False)),
                ('sn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('location', models.CharField(blank=True, db_index=True, max_length=32)),
                ('province', models.CharField(blank=True, db_index=True, max_length=32)),
                ('city', models.CharField(blank=True, db_index=True, max_length=32)),
                ('district', models.CharField(blank=True, db_index=True, max_length=32)),
                ('towerFrom', models.IntegerField(blank=True, null=True)),
                ('towerTo', models.IntegerField(blank=True, null=True)),
                ('idInTower', models.IntegerField(blank=True, null=True)),
                ('identity', models.CharField(blank=True, max_length=64)),
                ('protocolVersion', models.IntegerField(blank=True, null=True)),
                ('hardwareVersion', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('carrier', models.SmallIntegerField(blank=True, null=True)),
                ('backupCarrier', models.SmallIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('operators', models.ManyToManyField(blank=True, related_name='units', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedunits', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitAlarmSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almDistSet1', models.IntegerField()),
                ('almDistSet2', models.IntegerField()),
                ('almDistSet3', models.IntegerField()),
                ('sensMode', models.BooleanField(default=False)),
                ('beepEnable', models.BooleanField(default=True)),
                ('weatherMask', models.BooleanField(default=False)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarmSettings', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitCameraSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camEnable1', models.BooleanField(default=True)),
                ('camLgtEnhance1', models.BooleanField(default=True)),
                ('camMode1', models.SmallIntegerField()),
                ('camResolution1', models.SmallIntegerField()),
                ('camFrameRate1', models.SmallIntegerField()),
                ('camVideoTimeLen1', models.SmallIntegerField()),
                ('camTimingIntv11', models.SmallIntegerField()),
                ('camEnable2', models.BooleanField(default=True)),
                ('camLgtEnhance2', models.BooleanField(default=True)),
                ('camMode2', models.SmallIntegerField()),
                ('camResolution2', models.SmallIntegerField()),
                ('camFrameRate2', models.SmallIntegerField()),
                ('camVideoTimeLen2', models.SmallIntegerField()),
                ('camTimingIntv12', models.SmallIntegerField()),
                ('camEnable3', models.BooleanField(default=True)),
                ('camLgtEnhance3', models.BooleanField(default=True)),
                ('camMode3', models.SmallIntegerField()),
                ('camResolution3', models.SmallIntegerField()),
                ('camFrameRate3', models.SmallIntegerField()),
                ('camVideoTimeLen3', models.SmallIntegerField()),
                ('camTimingIntv13', models.SmallIntegerField()),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cameraSettings', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitNetworkSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serverIp', models.CharField(default='121.41.25.64', max_length=32)),
                ('serverPort', models.IntegerField(default='8682')),
                ('gsmApn', models.CharField(blank=True, max_length=32)),
                ('gsmUserName', models.CharField(blank=True, max_length=32)),
                ('gsmPassword', models.CharField(blank=True, max_length=32)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networkSettings', to='units.Unit')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
