# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='unitalarmsettings',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='unitcamerasettings',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='unitnetworksettings',
            options={'ordering': ['-createdAt', '-updatedAt']},
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='unitalarmsettings',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='unitalarmsettings',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='unitcamerasettings',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='unitcamerasettings',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='unitnetworksettings',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='unitnetworksettings',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
