# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='units.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='phonenum',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'city'), (1, 'line'), (2, 'unit')]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='voltage',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
