# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-15 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20170807_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitcamerasettings',
            old_name='camTimingIntv11',
            new_name='camTimingIntvl1',
        ),
        migrations.RenameField(
            model_name='unitcamerasettings',
            old_name='camTimingIntv12',
            new_name='camTimingIntvl2',
        ),
        migrations.RenameField(
            model_name='unitcamerasettings',
            old_name='camTimingIntv13',
            new_name='camTimingIntvl3',
        ),
    ]
