# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20170519_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitalertsettings',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alertsettings', to='units.Unit'),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networksettings', to='units.Unit'),
        ),
    ]
