# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20170520_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='csq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='networkstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='networktype',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='resetcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='retrycount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='serverport',
            field=models.IntegerField(default='8682'),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitnetworksettings',
            name='transfertype',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
