# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20170717_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitalertsettings',
            name='picinterval',
            field=models.SmallIntegerField(default=0),
        ),
    ]
